---
title: "viz_part"
subtitle: "Part 2"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
```

##Load the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```

## Remember this plot..?

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color= name)) + 
  geom_point(alpha= .5)
  
```
##Labels 

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color= name)) + 
  geom_point(alpha= .5) +
  labs(
    title="temperature plot",
    x="Min Daily Temperature (C)",
    y="Max Daily Temperature (C)",
    caption="Data from rnoaa package"
  )
```

## Scales

```{r}

weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color= name)) + 
  geom_point(alpha= .5) +
  labs(
    title="temperature plot",
    x="Min Daily Temperature (C)",
    y="Max Daily Temperature (C)",
    caption="Data from rnoaa package"
  ) +
  scale_x_continuous(
    breaks= c(-15, 0, 15),
    labels=c("-15 C", "0", "15")
    
  )+
  scale_y_continuous(
    position="right"
  )
```
## Look at color scales

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color= name)) + 
  geom_point(alpha= .5) +
  labs(
    title="temperature plot",
    x="Min Daily Temperature (C)",
    y="Max Daily Temperature (C)",
    caption="Data from rnoaa package"
  )+
  scale_color_hue(
    name="Location",
    h=c(100,200))
```

## More colors

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color= name)) + 
  geom_point(alpha= .5) +
  labs(
    title="temperature plot",
    x="Min Daily Temperature (C)",
    y="Max Daily Temperature (C)",
    caption="Data from rnoaa package"
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE)
```
## Themes

Shift the legend
```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color= name)) + 
  geom_point(alpha= .5) +
  labs(
    title="temperature plot",
    x="Min Daily Temperature (C)",
    y="Max Daily Temperature (C)",
    caption="Data from rnoaa package"
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE)+
  theme(legend.position= "bottom")
```
Shift overall theme

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color= name)) + 
  geom_point(alpha= .5) +
  labs(
    title="temperature plot",
    x="Min Daily Temperature (C)",
    y="Max Daily Temperature (C)",
    caption="Data from rnoaa package"
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE)+
  theme_minimal()+
  theme(legend.position="bottom")
```
## Setting options

```{r, eval=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width=6,
  fig.asp= .6,
  out.width= "90%"
)
theme_set(theme_minimal()+theme(legend.position="bottom"))

options(
  ggplot2.continuous.color="viridis",
  ggplot2.continuous.fill= "viridis"
)

scale_color_discrete= scale_color_viridis_d
scale_fill_discrete= scale_color_viridis_d
```

##Data args in `geom`

```{r}
central_park=
  weather_df %>% 
  filter(name=="CentralPark_NY")

waikiki=
  weather_df %>% 
  filter(name=="Waikiki_HA")

ggplot(data=waikiki, aes(x= date, y=tmax, color=name))+
  geom_point()+
  geom_line(data=central_park)
```
## `patchwork`


what happens when you want multipanel plots but can't facet?

```{r}
tmax_tmin_p=
  weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color=name))+
  geom_point(alpha=.5)+
  theme(legend.position="none")

prcp_dens_p=
  weather_df %>% 
  filter(prcp>0) %>% 
  ggplot(aes(x=prcp, fill=name))+
  geom_density(alpha=0.5)

tmax_date_p=
  weather_df %>% 
  ggplot(aes(x=date, y=tmax, color=name))+
  geom_point()+
  geom_smooth(se=FALSE)+
  theme(legend.position="none")

tmax_tmin_p+tmax_date_p
```

## Data Manipulation

Control your factors

```{r}
 weather_df %>% 
  mutate(
    name=factor(name),
    name=forcats::fct_relevel(name, c("Waikiki_HA"))
  ) %>% 
  ggplot(aes(x=name, y=tmax, fill=name))+
  geom_violin(alpha=.5)
```
What if I wanted densities for tmin and tmax simul?

```{r}
weather_df %>% 
  filter(name=="CentralPark_NY") %>% 
  pivot_longer(
    tmax:tmin,
    names_to="observation",
    values_to="temperatures"
    
  ) %>% 
  ggplot(aes(x=temperatures, fill=observation))+
           geom_density(alpha=0.5)+
            facet_grid(.~ name)
```

